set search_path=public,extensions;
create extension if not exists vector;
create extension if not exists pgcrypto;
create table profiles (id uuid primary key references auth.users(id) on delete cascade, display_name text not null default '', created_at timestamptz not null default now());
create table groups (id uuid primary key default gen_random_uuid(), name text not null check(length(name) between 1 and 100), timezone text not null default 'Asia/Seoul', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table group_members (group_id uuid references groups on delete cascade, user_id uuid references auth.users on delete cascade, role text not null check(role in ('owner','admin','member')), created_at timestamptz not null default now(), primary key(group_id,user_id));
create unique index one_owner on group_members(group_id) where role='owner';
create table group_invites (id uuid primary key default gen_random_uuid(),group_id uuid not null references groups on delete cascade, token_hash text not null unique, created_by uuid not null references auth.users, expires_at timestamptz not null, used_at timestamptz, revoked_at timestamptz, created_at timestamptz not null default now());
create table posts(id uuid primary key default gen_random_uuid(),group_id uuid not null references groups on delete cascade,author_id uuid not null references auth.users,title text not null check(length(title) between 1 and 200),body text not null check(length(body) between 1 and 20000),kind text not null check(kind in ('general','question','notice')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(group_id,id));
create table comments(id uuid primary key default gen_random_uuid(),group_id uuid not null,post_id uuid not null,author_id uuid not null references auth.users,body text not null check(length(body) between 1 and 5000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(group_id,post_id) references posts(group_id,id) on delete cascade);
create table events(id uuid primary key default gen_random_uuid(),group_id uuid not null references groups on delete cascade,author_id uuid not null references auth.users,title text not null check(length(title) between 1 and 200),description text not null default '',location text not null default '',starts_at timestamptz not null,ends_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at>starts_at),unique(group_id,id));
create table event_attendees(group_id uuid not null,event_id uuid not null,user_id uuid not null references auth.users,status text not null check(status in ('going','not_going','maybe')),updated_at timestamptz not null default now(),primary key(group_id,event_id,user_id),foreign key(group_id,event_id) references events(group_id,id) on delete cascade,foreign key(group_id,user_id) references group_members on delete cascade);
create table documents(id uuid primary key default gen_random_uuid(),group_id uuid not null references groups on delete cascade,author_id uuid not null references auth.users,title text not null check(length(title) between 1 and 200),kind text not null check(kind in ('pdf','memo')),text_content text,storage_path text unique,size_bytes bigint,status text not null default 'pending' check(status in ('pending','processing','ready','failed')),error_code text,version integer not null default 1,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(group_id,id),check((kind='memo' and text_content is not null and length(text_content)<=100000) or (kind='pdf' and storage_path is not null and size_bytes between 1 and 20971520)));
create table document_chunks(id uuid primary key default gen_random_uuid(),group_id uuid not null,document_id uuid not null,version integer not null,chunk_index integer not null,page_number integer,content text not null,embedding vector(1536) not null,created_at timestamptz not null default now(),foreign key(group_id,document_id) references documents(group_id,id) on delete cascade,unique(document_id,version,chunk_index));
create table chat_sessions(id uuid primary key default gen_random_uuid(),group_id uuid not null references groups on delete cascade,user_id uuid not null references auth.users,title text not null default '새 대화',created_at timestamptz not null default now(),unique(group_id,id),foreign key(group_id,user_id) references group_members on delete cascade);
create table chat_messages(sequence bigint generated always as identity, id uuid primary key default gen_random_uuid(),group_id uuid not null,session_id uuid not null,role text not null check(role in ('user','assistant')),content text not null,citations jsonb not null default '[]',grounded boolean not null default false,created_at timestamptz not null default now(),foreign key(group_id,session_id) references chat_sessions(group_id,id) on delete cascade);
create table audit_logs(id uuid primary key default gen_random_uuid(),group_id uuid not null,actor_id uuid not null,action text not null,resource_id uuid,created_at timestamptz not null default now());
create index members_user on group_members(user_id);
create index posts_group_time on posts(group_id,created_at desc);
create index comments_group_post on comments(group_id,post_id,created_at);
create index events_group_start on events(group_id,starts_at);
create index docs_group on documents(group_id,status);
create index chunks_scope on document_chunks(group_id,document_id,version);
create index sessions_owner on chat_sessions(group_id,user_id,created_at desc);
create index messages_session on chat_messages(group_id,session_id,sequence);
create index invites_group on group_invites(group_id);
create index audits_group on audit_logs(group_id,created_at);
create function touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now();return new;end $$;
create trigger groups_updated before update on groups for each row execute function touch_updated_at();
create trigger posts_updated before update on posts for each row execute function touch_updated_at();
create trigger comments_updated before update on comments for each row execute function touch_updated_at();
create trigger events_updated before update on events for each row execute function touch_updated_at();
create trigger documents_updated before update on documents for each row execute function touch_updated_at();
create trigger event_attendees_updated before update on event_attendees for each row execute function touch_updated_at();
alter table profiles enable row level security;
revoke all on profiles from anon, authenticated;
alter table groups enable row level security;
revoke all on groups from anon, authenticated;
alter table group_members enable row level security;
revoke all on group_members from anon, authenticated;
alter table group_invites enable row level security;
revoke all on group_invites from anon, authenticated;
alter table posts enable row level security;
revoke all on posts from anon, authenticated;
alter table comments enable row level security;
revoke all on comments from anon, authenticated;
alter table events enable row level security;
revoke all on events from anon, authenticated;
alter table event_attendees enable row level security;
revoke all on event_attendees from anon, authenticated;
alter table documents enable row level security;
revoke all on documents from anon, authenticated;
alter table document_chunks enable row level security;
revoke all on document_chunks from anon, authenticated;
alter table chat_sessions enable row level security;
revoke all on chat_sessions from anon, authenticated;
alter table chat_messages enable row level security;
revoke all on chat_messages from anon, authenticated;
alter table audit_logs enable row level security;
revoke all on audit_logs from anon, authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values ('group-documents','group-documents',false,20971520,array['application/pdf']) on conflict(id) do update set public=false,file_size_limit=20971520,allowed_mime_types=array['application/pdf'];
-- No storage.object policies for anon/authenticated: signed URLs only through authorized API.
